org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft Properties
minecraft_version = 1.21.11
minecraft_version_supported = [1.21.4,1.21.11]
minecraft_version_lower = 1.21.1
minecraft_version_upper = 1.22.0

# File Name
minecraft_version_name = 1.21.4(-11)
archives_base_name = MoreBeehiveVariants

# Mod Properties

mod_id=quad-lolmbhv
mod_name=More Beehive Variants
mod_name_short=More Beehive Variants
mod_license=CC-BY-NC-SA-4.0
mod_version=1.2.4
mod_group_id=de.pnku.mbhv
mod_description=Adding beehive variants to Minecraft

# Quad Properties
quad_version=1.2.3